
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUY3ekNDQTllZ0F3SUJBZ0lKQUtHVG5mMngx
      cEgxTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdOTVFzd0NRWUQKVlFRR0V3SllXREVWTUJNR0ExVUVC
      d3dNUkdWbVlYVnNkQ0JEYVhSNU1Sd3dHZ1lEVlFRS0RCTkVaV1poZFd4MApJRU52YlhCaGJua2dU
      SFJrTVVrd1J3WURWUVFEREVCbGJHRnpkR2xqTFdWdWRpMXZjR1Z5WVhSdmNpMTNaV0pvCmIyOXJM
      WE5sY25acFkyVXVaV3hoYzNScFl5MWxibll0YjNCbGNtRjBiM0l0YzNsemRHVnRNQjRYRFRJeE1E
      TXkKTmpBNE1ETXpNVm9YRFRNeE1ETXlOREE0TURNek1Wb3dnWTB4Q3pBSkJnTlZCQVlUQWxoWU1S
      VXdFd1lEVlFRSApEQXhFWldaaGRXeDBJRU5wZEhreEhEQWFCZ05WQkFvTUUwUmxabUYxYkhRZ1Ey
      OXRjR0Z1ZVNCTWRHUXhTVEJICkJnTlZCQU1NUUdWc1lYTjBhV010Wlc1MkxXOXdaWEpoZEc5eUxY
      ZGxZbWh2YjJzdGMyVnlkbWxqWlM1bGJHRnoKZEdsakxXVnVkaTF2Y0dWeVlYUnZjaTF6ZVhOMFpX
      MHdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBdwpnZ0lLQW9JQ0FRRERSa1JOMmlBSU5L
      cTVuTWVGOFdWNkFTbmNKSkVWaXRJd0I4VHRjRFZBVXRrMzVBNmRiRFlVClkzcjlTV0ZpejRCZEwz
      aXh1MVQvMVZzNkRzdFdhNHpYbmxTM3Y5aTlkOU1IeTd1SmhwQnB6L0pOVzJmQWt0MGgKUGdrQ0xS
      V0tNS0Q0aWdJTE1YZTRhMXNOcHRlSWs5cEx0NWppNGI4RWZoU0dWeFVRT0VlWXRTaEhUY3diQXNl
      MgpPVUpnSXZxOWhjUWVjUWVOaE1oYnRzNmNyNjlPdGJFenhPWWwrSWJjeWtZRXZ1Ylg2bE1oL2Fw
      dnp1cHFQd1NJCllDM1pKVmNXbVlHYkFkVmZkRTFybEJXdGFVa0w5ZjU0RDJqcDlhTjd4d0dSR0Z0
      VkFqenFzZjdBeXFFMmNud1gKVVVoRzdzN2NkYWhpNm95dWVocnB1ZmxBSnREOEpGM3ltV2Vua0dC
      ejFyZitrWHhuYk91WDMreWMwNmxEYjhtSApFZGRFbXliSVV1ektpVVFabFpWa2J2Ni9Yb3NURDlE
      MTdSekZXdWQrMTNPN2ZGYWpaTFdaL2RTMHMyU3o1NnZsCnFJMXVPVThoTDlJWHRPbW1TcjZLTXdE
      R09GS1hnWUkxeVVSeHVuVkpGVVU2SUpTNUNNK2czU2EyOXhQc091R2kKRXIwcE9VemhaL2lxT0lo
      Vy9JUTNOK3BERnRIOXNjWFNKSHRiSUJWQklsRUZKSnNkblllclYyNncyRTZIT1F6cApXdzZsU05v
      V1FiN1doVGttV2Y1T1h0RkQyNGloa1Y5cTNaN3Bhd2p4MERtK3NtT2RUckxMeDVoMFNkTS9tbEdQ
      CnpETGg5TFVLaHZ4M0F6NnZ2TmxBZC9EcEx3OXNGcUtpWjgzcm9LTGU4L3pwZCt5NU9Jazhzd0lE
      QVFBQm8xQXcKVGpBZEJnTlZIUTRFRmdRVTZMbXcrekVia3RGM2FZd1MyRElMZWpJTzJ5NHdId1lE
      VlIwakJCZ3dGb0FVNkxtdworekVia3RGM2FZd1MyRElMZWpJTzJ5NHdEQVlEVlIwVEJBVXdBd0VC
      L3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFnRUFmbWZ0NnByenVycXBWN2FaYTVELzFxdFdPWmVi
      SFJ1R25lSU91NkJ2dzQrTnQyN05kV2VEWldiVDE4VFMKVUpUdGR6T3FFbHZMTUFFTlV0OTF2Ymdi
      aWs5RDIxcVZkVHZHYXhKMy9VZmhMbHZBNW5iOXZKTW5oc3R6RXlVOApIRlYyOUduSDhGZzJkT2ZC
      OEE3RE5CK1pOMjlyNnBxYXR0cHZhbE9NWEY4S2tqalUyMnJMNWdQdmpyMmlZQXhJCnBnMW8xWlFr
      bDZIUEtNVTMrdkFBcmdHRnA1dU5Rb0NVOEFtYjN3bVdNa2Q0VXgvN2ozYkNndmJTVGlKZEpSV3EK
      cXlnUDFYMURIb3R3RmtJd0ZjMldlMDhVMkpxS3JLKy9DS1RIV2tOT3RldklMbCtVMm5qNHAwM0x5
      YXRCN1lwNwpXYWdDS2xCa2hnVitFT1pIRWpYZDBueHg2VlovbHZ6aDdaTlR3dm9YR3AzZXhXd3hm
      YTVsaDQ0cXR5OUs3TjRTCjNSMEtlQU9RaXJRV1JpZkVRUVZjZDdza2ZkZ2oyam5KNmkrUXgxZ2sz
      NjdzVDU1bVl4WFhzMVI3Q1plWFRFQkMKelRmZVhOeTVHelArNFdSQ3QzbDVjL0Y2NmtZZXdLVWo2
      RExVRzlIMHp6NnVpTU5lNmxUQXRDTzdvMUFxcjlYZQpZS1MrTFNiMjlpb085b1EvV2djRUZVRWM3
      TXZabnVSTityZmlLNDd3ZVJ4dXRTdHVzUlJWY2pQQ3l2Yks4QTRJCmdFRy9nVE5pYWVFWldLK2Jp
      SDR2aGtvOXNuQVBwNlRReTJXeENjaHdYL0U1VnExdnUzeWVSeEk4Z05tc3o0b28KR0dsZzJJRWpv
      YndUZnJSK09XbWRHMDlPbUxFVTJlakdrZnB6UVRnWmxIdGhVZVE9Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0K
    service:
      name: webhook-service
      namespace: system
      path: /validate-qa-shouqianba-com-v1alpha1-sqbdeployment
  failurePolicy: Fail
  name: vsqbdeployment.kb.io
  rules:
  - apiGroups:
    - qa.shouqianba.com
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - sqbdeployments
