// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvMirror) DeepCopyInto(out *ElasticEnvMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvMirror.
func (in *ElasticEnvMirror) DeepCopy() *ElasticEnvMirror {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticEnvMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvMirrorList) DeepCopyInto(out *ElasticEnvMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticEnvMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvMirrorList.
func (in *ElasticEnvMirrorList) DeepCopy() *ElasticEnvMirrorList {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticEnvMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvMirrorSpec) DeepCopyInto(out *ElasticEnvMirrorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvMirrorSpec.
func (in *ElasticEnvMirrorSpec) DeepCopy() *ElasticEnvMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvMirrorStatus) DeepCopyInto(out *ElasticEnvMirrorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvMirrorStatus.
func (in *ElasticEnvMirrorStatus) DeepCopy() *ElasticEnvMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvMirrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvPlane) DeepCopyInto(out *ElasticEnvPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvPlane.
func (in *ElasticEnvPlane) DeepCopy() *ElasticEnvPlane {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticEnvPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvPlaneList) DeepCopyInto(out *ElasticEnvPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticEnvPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvPlaneList.
func (in *ElasticEnvPlaneList) DeepCopy() *ElasticEnvPlaneList {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticEnvPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvPlaneSpec) DeepCopyInto(out *ElasticEnvPlaneSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvPlaneSpec.
func (in *ElasticEnvPlaneSpec) DeepCopy() *ElasticEnvPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvPlaneStatus) DeepCopyInto(out *ElasticEnvPlaneStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvPlaneStatus.
func (in *ElasticEnvPlaneStatus) DeepCopy() *ElasticEnvPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvProject) DeepCopyInto(out *ElasticEnvProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvProject.
func (in *ElasticEnvProject) DeepCopy() *ElasticEnvProject {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticEnvProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvProjectList) DeepCopyInto(out *ElasticEnvProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticEnvProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvProjectList.
func (in *ElasticEnvProjectList) DeepCopy() *ElasticEnvProjectList {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticEnvProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvProjectSpec) DeepCopyInto(out *ElasticEnvProjectSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvProjectSpec.
func (in *ElasticEnvProjectSpec) DeepCopy() *ElasticEnvProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticEnvProjectStatus) DeepCopyInto(out *ElasticEnvProjectStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticEnvProjectStatus.
func (in *ElasticEnvProjectStatus) DeepCopy() *ElasticEnvProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticEnvProjectStatus)
	in.DeepCopyInto(out)
	return out
}
