name: ci

on:
  pull_request:
    branches:
    - master
  push:
    branchs:
    - release/*
    - hotfix/*
    - master
    tags:
    - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: v1.0.0
      DOCKER_IMAGE: wosai/elastic-env-operatpr
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Set up Kubebuilder
      run: |
        os=$(go env GOOS)
        arch=$(go env GOARCH)
        curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
        sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
    - name: Test Coverage Report
      run: bash <(curl -s https://codecov.io/bash)
    - name: Build and Release Docker Image
      uses: docker/build-push-action@v1
      with:
        registry: registry.wosai-inc.com
        username: ${{ secrets.SQB_REGISTRY_USERNAME }}
        password: ${{ secrets.SQB_REGISTRY_PASSWORD }}
        repository: registry.wosai-inc.com/qa/elastic-env-operator
        tag_with_ref: true
        tag_with_sha: true